export class datamonk {
    id:string;
    //ประเภทพระเครื่อง
    typeAmulet:string;
     //ชื่อพระเครื่อง
    nameAmulet:string;
     //พิมพ์พระเครื่อง
    shapeAmulet:string;
     //มวลสาร
    compoundAmulet:string;
     //ชื่อพระที่ปลุกเสก
    nameMonk:string;
    //วันที่ปลุกเสก
    dateConsecrate:string;
    //วัดที่ปลุกเสก
    temple:string;
    //จังหวัด
    province:string;
    //ชื่อเจ้าภาพ
    nameHost:string;
    //รหัสนำ(ขึ้นต้น)
    firstId:string;
    //ครั้งที่เจนรหัสในเดือน
    countGenIdOfMount:string;
    //จำนวนที่เจนรหัส
    amountGenId:string;
}